### ISSUE TITLE
Gitflow branch naming

### ISSUE THREAD

**Issue by Sitebase** [prose/prose#1020] opened 2017-03-23 10:49 UTC
We use git flow model at our company for working with git.
One of the conventions is that you name your branches like this `{type}/{name}` so for example `feature/webinar`.

When switching to such a branch in prose you'll end up on a URL like this:

```
http://prose.io/#ambassify/website/tree/feature/webinar
```

which results in a 404 page not found.

**Comment by dereklieu** [comment] 2017-03-23 11:10
Dupe of #841 
BTW I'd love some help on this if someone in your organization would be open to contributing a patch.

**Closed by dereklieu** 2017-03-23 11:10 UTC
