### ISSUE TITLE
It breaks the date when I update a post.

### ISSUE THREAD

**Issue by juliocesar-io** [prose/prose#810] opened 2015-02-01 05:53 UTC
It should put the current date but I get an empty string. Is there a problem or I have a misconfiguration ? 
![screenshot from 2015-02-01 00 44 11](https://cloud.githubusercontent.com/assets/5655753/5991188/7a32fb12-a9ab-11e4-98d3-2bbe3f7c659f.png)
~ On Linux/Firefox 35.

**Comment by mikemorris** [comment] 2015-02-02 15:40
Possible dupe of https://github.com/prose/prose/issues/637?

**Comment by uzi200** [comment] 2015-02-02 16:29
Oh for sure, but I already solved it with this option
``
date: CURRENT_DATETIME
``

**Comment by mikemorris** [comment] 2015-02-02 16:50
Is `CURRENT_DATETIME` working again? Last I checked it was [broken](https://github.com/prose/prose/issues/277).

**Comment by dereklieu** [comment] 2015-08-13 21:18
`CURRENT_DATETIME` is working on prose.io

```(yaml)
name: "date"
  field: 
    element: "hidden"
    value: "CURRENT_DATETIME"
```

Use `text` instead of `hidden` if you need to make it edit-able.

**Closed by dereklieu** 2015-08-13 21:18 UTC

**Comment by phillipadsmith** [comment] 2015-08-15 20:50
> CURRENT_DATETIME is working on prose.io

OMG. So awesome! :100:
