### ISSUE TITLE
Why does Prose.io ask for access to my private repos?

### ISSUE THREAD

**Issue by letsgetrandy** [prose/prose#896] opened 2015-11-03 16:12 UTC
I don't want to give unknown third-parties access to my company's private repos, but this cannot be deselected during the authentication process.

Until this is changed, I cannot try out this tool.

**Comment by mikemorris** [comment] 2015-11-03 16:22
Dupe of https://github.com/prose/prose/issues/126

**Closed by mikemorris** 2015-11-03 16:22 UTC
