### ISSUE TITLE
Adding new file boots me out?

### ISSUE THREAD

**Issue by millerpils** [prose/prose#836] opened 2015-05-14 15:47 UTC
Hi folks,

When I add a new post using Prose and go to commit, it sends me back to the first screen after login with no errors and does not add the file. I've tried logging out/in freshly but it's still the same. Editing files works a treat.

In addition, adding meta data such as the block below seems to lock out any further changes being committed?

```
layout: default
title: Banners
modal-id: banners
category: agencies
```

Note that I don't have an configuration set in my YAML file - perhaps that is a pre-requisite?

**Comment by dereklieu** [comment] 2015-05-14 18:12
Hi @millerpils 

Thanks for reporting. There are a few known issues around using the raw metadata editor, such as #623. I and a few others are working on a fix, but it's not completed at the moment.

About adding a new post: if you don't use the metadata editor while creating a new post, does it still kick you out? Or does it allow you to create a new post so long as you don't touch that metadata editor?

**Comment by millerpils** [comment] 2015-05-15 08:19
Hi, thanks for getting back to me.

It posts a new one no problem with no meta. Unfortunately for us, we need the meta to drive the titles and menu system. 

As an aside, I've noticed that when editing and saving an established post, it wraps ``modal-id:`` in quotes. It doesn't cause any harm but thought I'd mention it.

**Comment by dereklieu** [comment] 2015-05-19 20:54
Yup, so this looks like it's caused by pre-existing metadata issues. Sorry I can't tell you it's fixed now, but hopefully I can tell you it's fixed very soon.

Can you explain more about `modal-id`? Is that an element in your meta data?

**Comment by millerpils** [comment] 2015-05-20 08:29
Cool. Modal-id is a bit of meta data we use as a URL hash for the menu.

**Comment by sgregson** [comment] 2015-07-21 13:23
is there an alternate workflow for adding YAML frontmatter within prose.io? Adding it into the post body appears to create multiple blocks as below. Alternatively, is there opposition to a "Is Alpha" tooltip on the raw metadata editor?

Output from inlining frontmatter in the post body:
```
---
published: false
---

---
layout: post
---
```

**Comment by phillipadsmith** [comment] 2015-08-09 00:40
@dereklieu Works for me from branch 'metadata-fixes' :+1:

**Comment by dereklieu** [comment] 2015-08-14 20:41
Raw editor is working as of #862 and now deployed to prose.io. 

I think the quotes wrapping is just what js-yaml does for strings with special characters such as dashes, but if it's not causing issues then I'm just going to leave that as is.

**Closed by dereklieu** 2015-08-14 20:41 UTC
