### ISSUE TITLE
prose.io

### ISSUE THREAD

**Issue by miwilc** [prose/prose#999] opened 2016-09-15 12:56 UTC
the website is now running unsecured http connections by default  ,
https gives a **ERR_CERT_COMMON_NAME_INVALID**
on viewing the crt it was given to *.github.io
This is a problem.

**Comment by dereklieu** [comment] 2016-09-15 14:32
Prose is hosted on Github Pages, which still doesn't support SSL for custom domain names. This is probably going to prove a dealbreaker for continuing to host Prose on Github pages, I'm looking to move to something like S3 once I get some time to work on it.

I think what has changed since I last looked into this is that now https://prose.github.io/prose redirects to vanilla http://prose.io. This is pretty annoying. 

Since this ticket is really an issue of not having SSL on prose, I'm closing it as a dupe of #883.

**Closed by dereklieu** 2016-09-15 14:32 UTC
