### ISSUE TITLE
Prose cannot handle slash branches e.g f/newfeature

### ISSUE THREAD

**Issue by richardofortune** [prose/prose#987] opened 2016-06-30 22:55 UTC
This doesn't look to be a url encoding issue. 

**Repro steps:**

1. Using Prose navigate to a repo that has branches with slashes in the name. 
2. Select a branch with a slash in the name e.g f/branch

**Results:**
Page 404s when it tries to load the branch.

**Comment by dereklieu** [comment] 2016-06-30 22:58
Unfortunately, a known issue. Duplicate of #841.

I'd love to review a PR to fix this. Diagnosis in the ticket I linked to.

**Closed by dereklieu** 2016-06-30 22:58 UTC
