### ISSUE TITLE
New Deployments ?

### ISSUE THREAD

**Issue by thiagohersan** [prose/prose#1136] opened 2023-06-14 23:52 UTC
Hello.
Love the project. First issue. Not necessarily code related.

I noticed there has been some activity on the master branch, but the hosted app on https://prose.io/ hasn't picked those up.

The gh-pages branch hasn't had a bump since 2018.
This probably has to do with Travis-CI being all wonky and not free now.

Would a github action file/script help ?

**Comment by babbitt** [comment] 2024-01-13 03:03
Hey there @thiagohersan. I've been trying to work on getting the project back into motion. The PR above will move prose over to gh-pages and restart CD. If you can give that a thumbs up hopefully the maintainers will see and merge.

In the meantime, I'm currently hosting my own fork with some bugfixes and features I've worked on @ [joebabbitt.com/prosa](https://joebabbitt.com/prosa). Since I want to avoid standing up my own gatekeeper instance and keep everything client-side, I've enabled login via github PAR token. ([You'll need to create a token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens) with the repo and user scopes to login). 

Hopefully that helps!

**Comment by thiagohersan** [comment] 2024-01-13 17:15
This is wonderful.

I meant to make a github action script, but since I never heard anything from anyone here I just kind of forgot about it.

Thanks so much.

**Comment by babbitt** [comment] 2024-01-15 06:37
Closing this as #1142 has merged and deployments are [confirmed working](https://github.com/prose/prose/actions/runs/7516138905) at [prose.io](https://prose.io/) :partying_face:

**Closed by babbitt** 2024-01-15 06:37 UTC

**Comment by thiagohersan** [comment] 2024-01-15 16:44
Wonderful. Thanks a bunch ! 🎉⚡️🥂
