### ISSUE TITLE
Can't Upload Image

### ISSUE THREAD

**Issue by agarrharr** [prose/prose#849] opened 2015-07-04 19:43 UTC
I can't upload an image. Whenever I try, it takes me back to the main page (http://prose.io/#username) and there is an error in the console:

```
Uncaught TypeError: Cannot read property 'media' of undefined
prose.min.js:8
```

I've tried running it locally and on prose.io

I've also tried using the file picker and dragging and dropping

**Comment by SchnWalter** [comment] 2015-07-08 18:17
Are you sure this is still the case? Could you please check with the latest code.  I've created a PR exactly for this issue, see #846.

**Comment by aharris88** [comment] 2015-07-08 22:28
I am not able to upload an image when I don't have a `_config.yml` file, but I just created one and added this to it:

    prose:
      media: "img"

And then I was able to upload an image.

I thought that the default behavior would be that it would upload the image in the current directory of the file that I'm editing.

I also tried uploading an image with an empty _config.yml file, and it had the same error. So it seems like image uploads is broken unless you have the media config set.

**Comment by SchnWalter** [comment] 2015-07-08 22:41
At first I also was under the impression that by default you will upload in the current directory, and that you could provide an absolute path or a relative path.  That is why I also suggested a change of the description for that widget in #850

**Comment by dereklieu** [comment] 2015-08-11 17:55
#864 would seem to fix the issue where, if the `media` path is not defined in `_config.yml` or `_prose.yml`, it defaults to the current directory.

**Comment by aharris88** [comment] 2016-04-16 04:40
This is definitely fixed. 👍

**Comment by chocmake** [comment] 2024-01-26 23:16
Just seeking some clarification on this. Has the image uploading feature being working for anyone since?

As I'm finding in my repos that neither when the `_config.yml` has any `prose` values (where according to what I'm reading it should upload to the current directly) nor when the `media: '<dir>'` value is added does image uploading seem supported.

The following is a screenshot of how the image panel appears when the `media` value is defined:

![Insert Image area](https://github.com/prose/prose/assets/34178938/1ae8966d-95eb-4938-9e3d-31e7ebfe7d00)

Tested on Firefox in both Windows and Linux (and Chromium in Linux) and drag-and-dropping images has no effect on either the text field or Insert Image area. Is it just me or is this broken currently?

**Comment by babbitt** [comment] 2024-01-27 05:45
> Just seeking some clarification on this. Has the image uploading feature being working for anyone since?
> Is it just me or is this broken currently?

Hey there @chocmake. I've just recently released some updates in relation to images but image uploading should have and continue to work. The upload panel should look something like this. (This screenshot was taken from [prose.io](https://prose.io) on Firefox)
![image](https://github.com/prose/prose/assets/10392896/0c18ef63-1399-4d47-beee-74b8c6380d5a)

If the repo is public can you provide a link so I can investigate? 
Would you also mind checking the developer console and seeing if there are any error logs?

**Comment by babbitt** [comment] 2024-01-27 05:51
Just doing a bit of preliminary research the only thing I'm seeing that could trigger the behavior you're seeing would be if you don't have permission to push to the repository
https://github.com/prose/prose/blob/468f29265cd79ccb9e3a876879eb73a283045d96/templates/dialogs/media.html#L6
https://github.com/prose/prose/blob/468f29265cd79ccb9e3a876879eb73a283045d96/app/models/file.js#L60

Do you have write access to the repo @chocmake?

I think the code is written as expected as if you don't have access to push to the repo I'm not sure how you'd be able to upload an image to it. 

If I'm missing a use case let me know and we can work on a bug/feature request for it.

**Comment by chocmake** [comment] 2024-01-27 13:38
> Do you have write access to the repo @chocmake?

I have direct write access, yeah. However I don't personally use Prose for commits so don't have it authorized with my account (some others that use the repo who lack direct write access have authorized Prose.io with their accounts though).

For my own clarity, if a repo has users who lack direct write permissions to a repo but authorize Prose with their accounts, is the behavior of Prose.io that images are uploaded to some branch of a fork on their own account at the point of interacting with the Prose.io UI (rather than waiting until they press 'Submit Change Request')?

As my experience above could be due to being under the impression the Prose.io session is a temporary state until submitting a PR, which appears to be the case for text but I assumed would also be the case for uploading images but I could be mistaken.

**Comment by babbitt** [comment] 2024-01-27 20:47
I think there's a lot of terms being used that may be leading to some confusion.
Prose uploads images at the time of upload (immediately) to the main branch, so **if a user does not have write access to the default branch they will be unable to upload images (they will not see what I saw in the screenshot)**.

Prose isn't very intelligent in terms of opening PR's (you'll notice that two changes to the same file successively will open 2 separate PR's instead of updating 1 branch), hence image uploading is restricted to users who can commit directly.

In order to implement what you're looking for (contributors without write access to upload images via PR). A state system (which doesn't really currently exist) would need to be built/rewritten and then the image upload to branch function could be implemented.

If that's something you're interested in put in a [feature request](https://github.com/prose/prose/issues/new?assignees=&labels=enhancement&projects=&template=feature_request.md&title=%5BFEAT%5D)

Prose is a legacy project. I'm the only active maintainer and I've only picked up the project quite recently. If you're interested in the feature and have the time it would be great if you could put in a PR. If that's something you're interested in taking on I can point you to the right places to start looking in the code base as I've been doing some work there recently. 

Going to re-close this as for now Prose is working as designed, probably just not an optimal solution.

**Closed by babbitt** 2024-01-27 20:47 UTC
