### ISSUE TITLE
Unauthenticated/unauthorized pull request broken

### ISSUE THREAD

**Issue by edrex** [prose/prose#540] opened 2013-07-29 19:05 UTC
I added an "edit this page" link to my Jekyll site. Clicking as an anonymous (not signed in to github) or unauthorized (but signed in) user results in the below:

```
Failed to load resource: the server responded with a status of 404 (Not Found) https://api.github.com/repos/edrex/edrex.github.io/forks
Uncaught SyntaxError: Unexpected token u prose.min.js:18
Uncaught TypeError: Cannot set property 'disabled' of undefined prose.min.js:22
```

**Comment by fulldecent** [comment] 2015-02-03 20:32
Hello and thank you for this issue report. There have been several point releases in Prose since this issue was opened and there has not been much discussion here. I wanted to ask if you could please assist in confirming this is still an issue in the latest version of the product. If it is fixed, please close this issue :-)

Also, if possible could you please

  * Find out if this only affects certain browsers
  * Create a test case -- a list of steps we can perform to reproduce the problem
  * Enable web developer extensions and report the Javascript error message. And when in doubt, be over-descriptive of the bug and how you discovered it.

Since this project is looking for new maintainers (#743), it will be helpful if users can double check the old issues and delete ones that are fixed. This will be super helpful for the new team that works on moving this project forward.

I'm sorry this message is impersonal. And thanks for your help!

**Comment by phillipadsmith** [comment] 2015-10-18 22:23
Closing this issue, as it is being tracked and discussed more actively in #643.

**Closed by phillipadsmith** 2015-10-18 22:23 UTC
Labels: bug
